-- drop table if exists paid_parking.entry;
create table paid_parking.entry (
	id integer not null primary key generated by default as identity,
	plate text not null,
	msisdn text not null,
	activation_time timestamp with time zone not null default current_timestamp,
	expiration_time timestamp with time zone not null,
	location_id integer not null references paid_parking.region(id)
);

-- drop type if exists paid_parking.pp_business_hours
create type paid_parking.pp_business_hours as (
 dow integer, -- 1 is Monday, 7 is Sunday
 pp_from time with time zone,
 pp_till time with time zone
);

-- drop table if exists paid_parking.region;
create table paid_parking.region (
 id integer not null primary key generated by default as identity,
 name text,
 price numeric not null,
 period interval not null,
 business_hours paid_parking.pp_business_hours[]
);

create or replace trigger forbid_update_and_delete
before update or delete on paid_parking.entry 
for each row execute function paid_parking.forget_it();

create or replace trigger calculate_expiration
before insert on paid_parking.entry
for each row execute function paid_parking.calculate_expiration_f();

create or replace function paid_parking.calculate_expiration_f()
returns trigger language plpgsql as
$$
declare
	remaining_time interval;
begin
 select period from paid_parking.region where id = new.location_id 
 into remaining_time;
 new.expiration_time := new.activation_time + remaining_time;
 return new;
end;
$$;

create or replace function paid_parking.forget_it() 
returns trigger language plpgsql as
$$
begin
 raise log 'Attempt to % on % by %', TG_OP, current_timestamp, current_user;
 return null;
end;
$$;

insert into region (price, period, name) values (1.50, '1 hour', 'Златица');
select * from region;


insert into entry(plate, msisdn, activation_time, expiration_time, location_id)
values ('CB4599KB', '359888123456', now(), now() + interval '1.5 hours', 1);

insert into entry(plate, msisdn, activation_time, location_id)
values ('CB4599KB', '359888123456', now() + interval '1.5 hours', 1);

select * from entry;

delete from entry where true;
update entry set msisdn = 'whatever';
